### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by tae898** [iglu-contest/iglu#2]
`python setup.py install`

throws an error:

```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 54s

...

raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./gradlew', '-g', 'run/gradle', 'shadowJar']' returned non-zero exit status 1.

```

**Comment by artemZholus** [comment]
Please, show the full error log. There should be a Java exception that caused the installation error.
But I also assume you are using wrong version of Java. Can you please show the output of `java -version` ?

**Comment by tae898** [comment]
Below is the full error

```
Welcome to Gradle 4.10.2!

Here are the highlights of this release:
 - Incremental Java compilation by default
 - Periodic Gradle caches cleanup
 - Gradle Kotlin DSL 1.0-RC6
 - Nested included builds
 - SNAPSHOT plugin versions in the `plugins {}` block

For more details see https://docs.gradle.org/4.10.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Minecraft'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.github.brandonhoughton:ForgeGradle:FG_2.2_patched-SNAPSHOT.
     Required by:
         project :
      > Could not resolve com.github.brandonhoughton:ForgeGradle:FG_2.2_patched-SNAPSHOT.
         > Unable to load Maven meta-data from https://jitpack.io/com/github/brandonhoughton/ForgeGradle/FG_2.2_patched-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://jitpack.io/com/github/brandonhoughton/ForgeGradle/FG_2.2_patched-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://jitpack.io/com/github/brandonhoughton/ForgeGradle/FG_2.2_patched-SNAPSHOT/maven-metadata.xml'.
                  > Read timed out
   > Could not resolve com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:1.2.4.
     Required by:
         project :
      > Could not resolve com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:1.2.4.
         > Could not get resource 'https://jitpack.io/com/github/johnrengelman/shadow/com.github.johnrengelman.shadow.gradle.plugin/1.2.4/com.github.johnrengelman.shadow.gradle.plugin-1.2.4.pom'.
            > Could not HEAD 'https://jitpack.io/com/github/johnrengelman/shadow/com.github.johnrengelman.shadow.gradle.plugin/1.2.4/com.github.johnrengelman.shadow.gradle.plugin-1.2.4.pom'.
               > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
Traceback (most recent call last):
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-3vr4ycxf/minerl_patched-0.1.0/setup.py", line 155, in <module>
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/tmp/easy_install-3vr4ycxf/minerl_patched-0.1.0/setup.py", line 89, in build
  File "/tmp/easy_install-3vr4ycxf/minerl_patched-0.1.0/setup.py", line 142, in build_minecraft
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./gradlew', '-g', 'run/gradle', 'shadowJar']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    setup(
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 408, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 650, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 744, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
    dist = best[req.key] = env.best_match(
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 669, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1162, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
    run_setup(setup_script, args)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/sandbox.py", line 139, in resume
    raise exc.with_traceback(self._tb)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-3vr4ycxf/minerl_patched-0.1.0/setup.py", line 155, in <module>
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/tk/.virtualenvs/iglu/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/tmp/easy_install-3vr4ycxf/minerl_patched-0.1.0/setup.py", line 89, in build
  File "/tmp/easy_install-3vr4ycxf/minerl_patched-0.1.0/setup.py", line 142, in build_minecraft
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./gradlew', '-g', 'run/gradle', 'shadowJar']' returned non-zero exit status 1.
```

**Comment by tae898** [comment]
Below is the java version

```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode)
```

**Comment by tae898** [comment]
Wait, now I see that the error I got today is different from that of yesterday. Yesterday was a java compile error but today is a time out error.

**Comment by tae898** [comment]
Alright I fixed it and made a pull request. You can close this issue.

**Comment by artemZholus** [comment]
Thank you!
